### ISSUE TITLE
[topics] tracking issue

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#1479]
- [x] add support to generate pages for all enclosed places of a certain type\
- [ ] add support for charts with no-data
- [x] add a landing page, link to this instead of dropdown
- [ ] bar chart: specify criteria for places to show (by rank / size)
- [ ] more bar chart improvement
- [ ] add responsive layout
- [ ] remove date formatting from chart titles (add it to chart modules so it stays consistent)
- [ ] add support for links to paragraph text
- [ ] launch: add link to header and homepage
