### ISSUE TITLE
[download tool] tracking issue

### ISSUE THREAD

**Issue by chejennifer** [datacommonsorg/website#1746]
- [ ] Fix alignment in mobile
    - [ ] In mobile: can we align the “Select Variable” button to the right of the label “Variables”.
    - [ ] In mobile / desktop: same alignment for Edit Sources
- [ ] Download button is often out of the viewport. Should we put it in the footer like Timeline?
- [ ] Add units if available for the values
- [ ] Clickable chips like in timeline
- [ ] Update links to navigate to the data download tool
- [ ] Handle too much data from mixer
- [ ] Handle downloading too much data
- [ ] Allow users to select only 1 place
- [ ] show preview + download button when page is first loaded

**Comment by chejennifer** [comment]
not planned
