### ISSUE TITLE
[Map] geotiff tracking issue

### ISSUE THREAD

**Issue by chejennifer** [datacommonsorg/website#1774]
- [ ] leaf page
- [ ] show installations
- [x] handle per capita
- [ ] redirect action on place click
- [ ] setting the ideal view
- [ ] source attributions
- [ ] chart title
- [ ] unit
- [ ] full feature tooltip
- [x] dynamic resize

Additional details in this doc: https://docs.google.com/document/d/1PCO-OSh47FVNHqi-wamtDoJN1voj0gSnYOCpUzE-e1Y/edit?usp=sharing&resourcekey=0-fMSB3mznhrAQGX0-OszRkg

**Comment by chejennifer** [comment]
closing because we've put geotiffs on hold indefinitely
