### ISSUE TITLE
Choropleth TODO

### ISSUE THREAD

**Issue by beets** [datacommonsorg/website#491]
- [ ] Getting the exploreURL for the charts
- [ ] Getting the sources for the charts
- [ ] Clean up scales and units (eg. right now, I append unit to the end of the value, but when the unit is $, it should be appended to the front)
- [ ] Try using the date alignment for getting data for choropleth
- [ ] Deal with when the tooltip message is too long
- [ ] Using viridis or something else for the color scale
- [ ] make the colors of my choropleths match the colors of the category
- [ ] geojson type

**Comment by beets** [comment]
tracked in #422
